<div class="btn-group bootstrap-select">
              <button type="button" class="btn dropdown-toggle selectpicker btn-default" data-toggle="dropdown" title="Limit: Unlimited">
                  <span class="filter-option pull-left">Limit: Unlimited</span>&nbsp;
                  <div class="edmodo-caret"><img src="//assets.edmodo.com/bootstrap/select-dropdown-arrow-retina.png" width="10"></div>
              </button>
          </div>
